### ISSUE TITLE
Feature request: css classes for each level

### ISSUE THREAD

**Issue by bronestly** [grantwinney/table-of-contents-for-html-page#2]
Hey there

aaand another request: I am trying to add a custom css counter where only the second level of nested lists is counted. But not the third or fourth.

since with `ol > li > ol > li` all levels below are included as well, can you add a feature so that every heading level get its own class?
e.g. .toc-h2, toc-h3, .toc-h4 and so on...

Would be great addition

**Comment by grantwinney** [comment]
Untested, but try changing this line:

```javascript
output += "<ol style=\"margin-bottom:0px\"><li>";
```

To this:

```javascript
output += "<ol class=\"toc-h" + (prevLevel + 1) + "\" style=\"margin-bottom:0px\"><li>";
```
